name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          npm ci
          npm run build-only

      - name: Release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: peekaboo
